[package]
name = "asciibox"
version = "0.1.0"
authors = ["nobodygx"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }

[dependencies.adw]
package = "libadwaita"
version = "~0.6"