[package]
name = "asciibox"
version = "0.7.1"
authors = ["nobodygx"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
adw = { version = "0.6", package = "libadwaita", features = ["v1_5"] }
nom = "7.1.3"
svgbob = "0.7.2"
