#!/bin/bash

pwd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function update_translations() {
    podir="${pwd}/../../po"
    poname="POTFILES.in"
    pofnames="${podir}/${poname}"
    # remove old poname
    if [ -f "$pofnames" ]; then
        rm -f "${pofnames}"
    fi

    {
        # add warning
        echo "# DO NOT EDIT MANUALLY"
        echo "# This files is autogenerated by the CI pipeline."
        echo ""
        # add metadata files
        echo "# METADATA files"
        find data -name "*.in" -print | sort
        # add ui files
        echo "# UI files"
        find data -name "*.ui" -print | sort
        # add rust files
        echo "# RUST files"
        grep gettext src/ -r | grep .rs | cut -d: -f1 | uniq | sort
    } >>"$pofnames"
}

update_translations
